name: Build KMP App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: Android
            os: ubuntu-latest
            task: ":androidApp:assembleDebug"
            test_task: ":androidApp:testDebugUnitTest :shared:testAndroid"
          - target: Desktop
            os: ubuntu-latest
            task: ":desktopApp:assemble"
            test_task: ":desktopApp:test :shared:jvmTest"
          - target: Web
            os: ubuntu-latest
            task: ":webApp:wasmJsBrowserDistribution"
            test_task: ":webApp:wasmJsBrowserTest :shared:wasmJsBrowserTest"
          - target: iOS
            os: macos-latest
            task: ":shared:compileKotlinIosSimulatorArm64"
            test_task: ":shared:iosSimulatorArm64Test"

    runs-on: ${{ matrix.os }}
    name: Build & Unit Test ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build ${{ matrix.target }}
        run: ./gradlew ${{ matrix.task }}

      - name: Run Unit Tests ${{ matrix.target }}
        run: ./gradlew ${{ matrix.test_task }}
